### PR TITLE
Updated codeclimate and eslint configs

### PR DESCRIPTION
**Pull request by pk-nb**
@aesnyder @derekclee @bwebster @brandonc @ianisborn @mhuggins 

Hello there! I am submitted the final versions of the code climate and eslint updates back to our common repo. These changes are already running in Napa, watercress, pepperweed, daikon, and some packages. I believe they are ready to drop into each project.

Ruby repo owners: I need your help! Could you help me copy this config to all repos before the quarter is over? It would be nice to have as many repos as possible be on CC v2 before the quarter ends. You don't need to do anything with eslint (feel free to turn off eslint, coffeelint, and scsslint checks off after copying `.codeclimate.yml`.

I have dibs on any repos with eslint configs—due to the complicated autofixes I need to run on each repo before adopting the changes here. I believe the only things left are wasabiweed (which I will update as soon as it slows down) and some packages (shared-ui, etc).

Please PR back any additional paths that need to be ignored. I think I got them all after the upgrade to v2 (which no longer whitelists), but there may need to be a few more. If they are app specific files, just leave them in your repo and comment the lines that were added from the base.

Thanks!

### CODE REVIEW

File: .codeclimate.yml [hunk 1]
```diff
@@ -4,53 +4,114 @@
...
+  grep:
+    enabled: true
+    config:
+      patterns:
+        no-dot-only:
+          pattern: \.only
+          annotation: "Make sure not to commit `.only` in specs, as it disables the rest of the suite."
+          severity: blocker
+          path_patterns:
+          - "**/*_spec.rb"
```
Comment (bwebster) [inline .codeclimate.yml]: I think this is a JavaScript only thing.  There are usages of `.only` all over the Ruby specs in napa.

**Review by bwebster — COMMENTED** [review]
Noticed one thing

File: .codeclimate.yml (hunk 1 above)
Comment (pk-nb) [reply .codeclimate.yml]: Ah right—because of the activerecord method. I'll update to warn on `it.only` and `describe.only`, as that's something that can mess up rspec suites as well as JS

Comment (bwebster) [reply .codeclimate.yml]: I'm not sure you can do that in rspec?  I tried and got this `undefined method 'only'`.

Comment (pk-nb) [reply .codeclimate.yml]: ah I don't know why I thought that was a thing. I guess I can check for `fit` https://stackoverflow.com/a/22113489/1493191 but I don't know if anyone uses it

Comment (pk-nb) [reply .codeclimate.yml]: also `focus: true` or `:focus => true`

Comment (bwebster) [reply .codeclimate.yml]: Yes, those ☝️

Comment (bwebster) [reply .codeclimate.yml]: I'm good with simply taking `**/*_spec.rb` out of this rule.

**Comment by pk-nb** [comment]
@bwebster feedback addressed—I tested the config locally to make sure it picked them up correctly. Specified the different paths with extensions now to make sure the checks were independent on file type.

**Review by bwebster — APPROVED** [review]
LGTM

**Comment by pk-nb** [comment]
Going to merge—feel free to leave retro feedback
